name: Build with Jupyter Files Excluded

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Delete problematic Jupyter files
        run: |
          # Remove or rename Jupyter notebooks
          find . -name "*.ipynb" -exec mv {} {}.disabled \;
          # Also disable the plugin in _config.yml
          sed -i 's/jekyll-jupyter-notebook/#jekyll-jupyter-notebook/g' _config.yml
          sed -i '/^\s*- jekyll-jupyter-notebook/d' Gemfile
          # Create an empty exclude file if it doesn't exist already
          touch .jekyll-exclude

      - name: Build Jekyll site
        run: bundle exec jekyll build --trace --exclude-from .jekyll-exclude
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "_site/"

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2